# Docker-Compose Dosyası: "docker-compose.yml"
version: '3.8'
services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: employee-management-app
      ports:
         - '8070:3000'
      depends_on:
         database:
            condition: service_healthy
      environment:
         DB_HOST: database
         DB_PORT: 5432
         DB_USER: postgres
         DB_PASSWORD: 123456
         DB_NAME: management_systemDB
         DB_URL: postgres://postgres:123456@database:5432/management_systemDB
      volumes:
         - .:/usr/src/app
      entrypoint: ['sh', '-c', 'npm run migrate && npm start']

   database:
      image: postgres:15
      container_name: postgres-database
      restart: always
      ports:
         - '5432:5432'
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: 123456
         POSTGRES_DB: management_systemDB
      volumes:
         - db_data:/var/lib/postgresql/data
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      healthcheck:
         test: ['CMD-SHELL', 'pg_isready -U postgres']
         interval: 10s
         retries: 5

volumes:
   db_data:
